export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
